//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/PlayerInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""21ecf598-7425-485a-a34e-36d686aea4c9"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""bede4270-95d9-4c90-9e96-1972f439068c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""ff6c827f-a9b6-402c-887a-546aef4c4a8e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""40e776dc-26ab-44d3-8996-5b938c90ac6d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""7b379677-7156-4f60-bc40-4ea16f0d9b17"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillSlot_1"",
                    ""type"": ""Button"",
                    ""id"": ""f5758c7b-b0ad-4c5a-bf48-e3341122cb8a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillSlot_2"",
                    ""type"": ""Button"",
                    ""id"": ""63dcc384-e73e-4d3f-9146-6f34c710da08"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillSlot_3"",
                    ""type"": ""Button"",
                    ""id"": ""38d2340b-9191-4bda-b01e-29bd4ed094dd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillSlot_4"",
                    ""type"": ""Button"",
                    ""id"": ""c00e80cb-c1ed-49e3-bae3-3bb6e7f48d07"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillSlot_5"",
                    ""type"": ""Button"",
                    ""id"": ""aa3cb3b1-74ff-47fc-b3cc-cb2212f9dd09"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillSlot_6"",
                    ""type"": ""Button"",
                    ""id"": ""e9fa45e5-1e28-4c0d-aa1a-26a84fe5fe5c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillSlot_7"",
                    ""type"": ""Button"",
                    ""id"": ""178fe8b3-1580-4b55-a5a4-d6c757fca2c4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillSlot_8"",
                    ""type"": ""Button"",
                    ""id"": ""b331c523-43b2-4c44-be7e-448466a6d808"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillSlot_9"",
                    ""type"": ""Button"",
                    ""id"": ""15888f38-ca7e-45c7-8833-84d3b4b3f9e8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillSlot_10"",
                    ""type"": ""Button"",
                    ""id"": ""aad3d5c0-a283-4831-8c26-e2c8edc33ee5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillSlot_11"",
                    ""type"": ""Button"",
                    ""id"": ""4a1f8002-cdc1-4f11-9e55-2cba7bb444cb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillSlot_12"",
                    ""type"": ""Button"",
                    ""id"": ""b0c5d6e1-b927-4762-96db-52f68ac338f1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillSlot_13"",
                    ""type"": ""Button"",
                    ""id"": ""81030047-bf39-4ab8-8b88-82b31183a4f4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillSlot_14"",
                    ""type"": ""Button"",
                    ""id"": ""11561272-0406-4435-b40a-412a9f51e4a4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7c317701-f845-4f61-a46f-7f6a60330a57"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a9dd7818-fd9b-4e75-b522-242177c2a566"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e9e83f12-cccc-4131-8655-abbb2e756b9e"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""247e4c57-c3f3-40cc-9140-b519edd2e19f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""101ed450-1de5-4911-a72f-b5dd0a2f2209"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""35bdcac5-c844-4be3-9722-3175638f902e"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": "";PC"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf69379c-48c6-4812-8cfe-39a5e846bc52"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": "";PC"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0abc51f7-9cfd-4cd2-8182-9f6e42e7a755"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": "";PC"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""250d2f80-41e5-4c4c-9e08-3de067edd58b"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aef0eeea-65cd-40f3-bedf-da87f016c64a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillSlot_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac1e3347-2a6d-427d-b20f-6397ea24d165"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillSlot_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46fb3e07-dcf1-4dab-84be-37025a1a8569"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillSlot_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2bd6c60-96f3-4c64-8497-50e40d3b27fb"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillSlot_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed47657b-238b-4902-bef6-0e1dbd6e78a8"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillSlot_5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65b5d14d-2089-49c1-9a8b-14928c945a30"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillSlot_6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6b85206-7f72-4a63-a466-e657fbb75b2e"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillSlot_7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad7d2ca2-11b7-4ba3-9368-19b7f131ff0c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillSlot_8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a177e54b-4354-4004-8619-b8f4ba5dfa72"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillSlot_9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b2f0b7f-16e9-41de-a31b-55e6fa42c8d5"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillSlot_10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""188c8b11-56e2-4d9b-944e-67440e9593c6"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillSlot_11"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0adabf4-6d97-4661-b429-3cdcb4c59c94"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillSlot_12"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d7ac513-2a5e-40d9-bf52-92ef9e4e2a2b"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillSlot_13"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f12f5b9-fe52-4fd9-a6c8-74bff5089969"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillSlot_14"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Run = m_Player.FindAction("Run", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_SkillSlot_1 = m_Player.FindAction("SkillSlot_1", throwIfNotFound: true);
        m_Player_SkillSlot_2 = m_Player.FindAction("SkillSlot_2", throwIfNotFound: true);
        m_Player_SkillSlot_3 = m_Player.FindAction("SkillSlot_3", throwIfNotFound: true);
        m_Player_SkillSlot_4 = m_Player.FindAction("SkillSlot_4", throwIfNotFound: true);
        m_Player_SkillSlot_5 = m_Player.FindAction("SkillSlot_5", throwIfNotFound: true);
        m_Player_SkillSlot_6 = m_Player.FindAction("SkillSlot_6", throwIfNotFound: true);
        m_Player_SkillSlot_7 = m_Player.FindAction("SkillSlot_7", throwIfNotFound: true);
        m_Player_SkillSlot_8 = m_Player.FindAction("SkillSlot_8", throwIfNotFound: true);
        m_Player_SkillSlot_9 = m_Player.FindAction("SkillSlot_9", throwIfNotFound: true);
        m_Player_SkillSlot_10 = m_Player.FindAction("SkillSlot_10", throwIfNotFound: true);
        m_Player_SkillSlot_11 = m_Player.FindAction("SkillSlot_11", throwIfNotFound: true);
        m_Player_SkillSlot_12 = m_Player.FindAction("SkillSlot_12", throwIfNotFound: true);
        m_Player_SkillSlot_13 = m_Player.FindAction("SkillSlot_13", throwIfNotFound: true);
        m_Player_SkillSlot_14 = m_Player.FindAction("SkillSlot_14", throwIfNotFound: true);
    }

    ~@PlayerInputActions()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, PlayerInputActions.Player.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Run;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_SkillSlot_1;
    private readonly InputAction m_Player_SkillSlot_2;
    private readonly InputAction m_Player_SkillSlot_3;
    private readonly InputAction m_Player_SkillSlot_4;
    private readonly InputAction m_Player_SkillSlot_5;
    private readonly InputAction m_Player_SkillSlot_6;
    private readonly InputAction m_Player_SkillSlot_7;
    private readonly InputAction m_Player_SkillSlot_8;
    private readonly InputAction m_Player_SkillSlot_9;
    private readonly InputAction m_Player_SkillSlot_10;
    private readonly InputAction m_Player_SkillSlot_11;
    private readonly InputAction m_Player_SkillSlot_12;
    private readonly InputAction m_Player_SkillSlot_13;
    private readonly InputAction m_Player_SkillSlot_14;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player".
    /// </summary>
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_Player_Move;
        /// <summary>
        /// Provides access to the underlying input action "Player/Run".
        /// </summary>
        public InputAction @Run => m_Wrapper.m_Player_Run;
        /// <summary>
        /// Provides access to the underlying input action "Player/Jump".
        /// </summary>
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        /// <summary>
        /// Provides access to the underlying input action "Player/Attack".
        /// </summary>
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        /// <summary>
        /// Provides access to the underlying input action "Player/SkillSlot_1".
        /// </summary>
        public InputAction @SkillSlot_1 => m_Wrapper.m_Player_SkillSlot_1;
        /// <summary>
        /// Provides access to the underlying input action "Player/SkillSlot_2".
        /// </summary>
        public InputAction @SkillSlot_2 => m_Wrapper.m_Player_SkillSlot_2;
        /// <summary>
        /// Provides access to the underlying input action "Player/SkillSlot_3".
        /// </summary>
        public InputAction @SkillSlot_3 => m_Wrapper.m_Player_SkillSlot_3;
        /// <summary>
        /// Provides access to the underlying input action "Player/SkillSlot_4".
        /// </summary>
        public InputAction @SkillSlot_4 => m_Wrapper.m_Player_SkillSlot_4;
        /// <summary>
        /// Provides access to the underlying input action "Player/SkillSlot_5".
        /// </summary>
        public InputAction @SkillSlot_5 => m_Wrapper.m_Player_SkillSlot_5;
        /// <summary>
        /// Provides access to the underlying input action "Player/SkillSlot_6".
        /// </summary>
        public InputAction @SkillSlot_6 => m_Wrapper.m_Player_SkillSlot_6;
        /// <summary>
        /// Provides access to the underlying input action "Player/SkillSlot_7".
        /// </summary>
        public InputAction @SkillSlot_7 => m_Wrapper.m_Player_SkillSlot_7;
        /// <summary>
        /// Provides access to the underlying input action "Player/SkillSlot_8".
        /// </summary>
        public InputAction @SkillSlot_8 => m_Wrapper.m_Player_SkillSlot_8;
        /// <summary>
        /// Provides access to the underlying input action "Player/SkillSlot_9".
        /// </summary>
        public InputAction @SkillSlot_9 => m_Wrapper.m_Player_SkillSlot_9;
        /// <summary>
        /// Provides access to the underlying input action "Player/SkillSlot_10".
        /// </summary>
        public InputAction @SkillSlot_10 => m_Wrapper.m_Player_SkillSlot_10;
        /// <summary>
        /// Provides access to the underlying input action "Player/SkillSlot_11".
        /// </summary>
        public InputAction @SkillSlot_11 => m_Wrapper.m_Player_SkillSlot_11;
        /// <summary>
        /// Provides access to the underlying input action "Player/SkillSlot_12".
        /// </summary>
        public InputAction @SkillSlot_12 => m_Wrapper.m_Player_SkillSlot_12;
        /// <summary>
        /// Provides access to the underlying input action "Player/SkillSlot_13".
        /// </summary>
        public InputAction @SkillSlot_13 => m_Wrapper.m_Player_SkillSlot_13;
        /// <summary>
        /// Provides access to the underlying input action "Player/SkillSlot_14".
        /// </summary>
        public InputAction @SkillSlot_14 => m_Wrapper.m_Player_SkillSlot_14;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @SkillSlot_1.started += instance.OnSkillSlot_1;
            @SkillSlot_1.performed += instance.OnSkillSlot_1;
            @SkillSlot_1.canceled += instance.OnSkillSlot_1;
            @SkillSlot_2.started += instance.OnSkillSlot_2;
            @SkillSlot_2.performed += instance.OnSkillSlot_2;
            @SkillSlot_2.canceled += instance.OnSkillSlot_2;
            @SkillSlot_3.started += instance.OnSkillSlot_3;
            @SkillSlot_3.performed += instance.OnSkillSlot_3;
            @SkillSlot_3.canceled += instance.OnSkillSlot_3;
            @SkillSlot_4.started += instance.OnSkillSlot_4;
            @SkillSlot_4.performed += instance.OnSkillSlot_4;
            @SkillSlot_4.canceled += instance.OnSkillSlot_4;
            @SkillSlot_5.started += instance.OnSkillSlot_5;
            @SkillSlot_5.performed += instance.OnSkillSlot_5;
            @SkillSlot_5.canceled += instance.OnSkillSlot_5;
            @SkillSlot_6.started += instance.OnSkillSlot_6;
            @SkillSlot_6.performed += instance.OnSkillSlot_6;
            @SkillSlot_6.canceled += instance.OnSkillSlot_6;
            @SkillSlot_7.started += instance.OnSkillSlot_7;
            @SkillSlot_7.performed += instance.OnSkillSlot_7;
            @SkillSlot_7.canceled += instance.OnSkillSlot_7;
            @SkillSlot_8.started += instance.OnSkillSlot_8;
            @SkillSlot_8.performed += instance.OnSkillSlot_8;
            @SkillSlot_8.canceled += instance.OnSkillSlot_8;
            @SkillSlot_9.started += instance.OnSkillSlot_9;
            @SkillSlot_9.performed += instance.OnSkillSlot_9;
            @SkillSlot_9.canceled += instance.OnSkillSlot_9;
            @SkillSlot_10.started += instance.OnSkillSlot_10;
            @SkillSlot_10.performed += instance.OnSkillSlot_10;
            @SkillSlot_10.canceled += instance.OnSkillSlot_10;
            @SkillSlot_11.started += instance.OnSkillSlot_11;
            @SkillSlot_11.performed += instance.OnSkillSlot_11;
            @SkillSlot_11.canceled += instance.OnSkillSlot_11;
            @SkillSlot_12.started += instance.OnSkillSlot_12;
            @SkillSlot_12.performed += instance.OnSkillSlot_12;
            @SkillSlot_12.canceled += instance.OnSkillSlot_12;
            @SkillSlot_13.started += instance.OnSkillSlot_13;
            @SkillSlot_13.performed += instance.OnSkillSlot_13;
            @SkillSlot_13.canceled += instance.OnSkillSlot_13;
            @SkillSlot_14.started += instance.OnSkillSlot_14;
            @SkillSlot_14.performed += instance.OnSkillSlot_14;
            @SkillSlot_14.canceled += instance.OnSkillSlot_14;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @SkillSlot_1.started -= instance.OnSkillSlot_1;
            @SkillSlot_1.performed -= instance.OnSkillSlot_1;
            @SkillSlot_1.canceled -= instance.OnSkillSlot_1;
            @SkillSlot_2.started -= instance.OnSkillSlot_2;
            @SkillSlot_2.performed -= instance.OnSkillSlot_2;
            @SkillSlot_2.canceled -= instance.OnSkillSlot_2;
            @SkillSlot_3.started -= instance.OnSkillSlot_3;
            @SkillSlot_3.performed -= instance.OnSkillSlot_3;
            @SkillSlot_3.canceled -= instance.OnSkillSlot_3;
            @SkillSlot_4.started -= instance.OnSkillSlot_4;
            @SkillSlot_4.performed -= instance.OnSkillSlot_4;
            @SkillSlot_4.canceled -= instance.OnSkillSlot_4;
            @SkillSlot_5.started -= instance.OnSkillSlot_5;
            @SkillSlot_5.performed -= instance.OnSkillSlot_5;
            @SkillSlot_5.canceled -= instance.OnSkillSlot_5;
            @SkillSlot_6.started -= instance.OnSkillSlot_6;
            @SkillSlot_6.performed -= instance.OnSkillSlot_6;
            @SkillSlot_6.canceled -= instance.OnSkillSlot_6;
            @SkillSlot_7.started -= instance.OnSkillSlot_7;
            @SkillSlot_7.performed -= instance.OnSkillSlot_7;
            @SkillSlot_7.canceled -= instance.OnSkillSlot_7;
            @SkillSlot_8.started -= instance.OnSkillSlot_8;
            @SkillSlot_8.performed -= instance.OnSkillSlot_8;
            @SkillSlot_8.canceled -= instance.OnSkillSlot_8;
            @SkillSlot_9.started -= instance.OnSkillSlot_9;
            @SkillSlot_9.performed -= instance.OnSkillSlot_9;
            @SkillSlot_9.canceled -= instance.OnSkillSlot_9;
            @SkillSlot_10.started -= instance.OnSkillSlot_10;
            @SkillSlot_10.performed -= instance.OnSkillSlot_10;
            @SkillSlot_10.canceled -= instance.OnSkillSlot_10;
            @SkillSlot_11.started -= instance.OnSkillSlot_11;
            @SkillSlot_11.performed -= instance.OnSkillSlot_11;
            @SkillSlot_11.canceled -= instance.OnSkillSlot_11;
            @SkillSlot_12.started -= instance.OnSkillSlot_12;
            @SkillSlot_12.performed -= instance.OnSkillSlot_12;
            @SkillSlot_12.canceled -= instance.OnSkillSlot_12;
            @SkillSlot_13.started -= instance.OnSkillSlot_13;
            @SkillSlot_13.performed -= instance.OnSkillSlot_13;
            @SkillSlot_13.canceled -= instance.OnSkillSlot_13;
            @SkillSlot_14.started -= instance.OnSkillSlot_14;
            @SkillSlot_14.performed -= instance.OnSkillSlot_14;
            @SkillSlot_14.canceled -= instance.OnSkillSlot_14;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />.
        /// </summary>
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerActions" /> instance referencing this action map.
    /// </summary>
    public PlayerActions @Player => new PlayerActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
    /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
    public interface IPlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Run" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRun(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJump(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Attack" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAttack(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SkillSlot_1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkillSlot_1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SkillSlot_2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkillSlot_2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SkillSlot_3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkillSlot_3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SkillSlot_4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkillSlot_4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SkillSlot_5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkillSlot_5(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SkillSlot_6" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkillSlot_6(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SkillSlot_7" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkillSlot_7(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SkillSlot_8" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkillSlot_8(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SkillSlot_9" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkillSlot_9(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SkillSlot_10" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkillSlot_10(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SkillSlot_11" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkillSlot_11(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SkillSlot_12" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkillSlot_12(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SkillSlot_13" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkillSlot_13(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SkillSlot_14" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkillSlot_14(InputAction.CallbackContext context);
    }
}
